export const FETCH_EPISODES = "FETCH_EPISODES";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const CHANGE_ICON_FAVORITE = "CHANGE_ICON_FAVORITE";
